version: "2"
checks:
  file-lines:
    config:
      threshold: 500
  method-lines:
    config:
      threshold: 100
  method-count:
    config:
      threshold: 25
  return-statements:
    enabled: false
  similar-code:
    enabled: false

exclude_patterns:
  - ".github/"
  - "build/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "**/vendor/"
  - "**/*.md"
  - "**/*.test.js"
  - "frontend/public/**"
  - "frontend/docs/**"
  - "frontend/styleguide/**"
  - "frontend/src/components/elements/ReactSlick/**"
  - "wordpress/wp-content/themes/**"
  - "!wordpress/wp-content/themes/MSG/**"
  - "wordpress/wp-content/plugins/**"
  - "!wordpress/wp-content/plugins/msg/**"
  - "wordpress/wp-content/plugins/msg/vendor/**"

plugins:
  eslint:
    enabled: true
    config:
      config: frontend/.eslintrc.json
  stylelint:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,inc,lib"
      standard: "WordPress,WordPress-Core"
    checks:
      WordPress PHP YodaConditions NotYoda:
        enabled: false
      WordPress NamingConventions ValidVariableName NotSnakeCase:
        enabled: false
      WordPress NamingConventions ValidFunctionName MethodNameInvalid:
        enabled: false
      WordPress Files FileName InvalidClassFileName:
        enabled: false
      WordPress Files FileName NotHyphenatedLowercase:
        enabled: false
      WordPress VIP PostsPerPage:
        enabled: false

